name: WaterRising
version: '${version}'
main: uk.jamieisgeek.waterrising.WaterRising
api-version: 1.19
depend:
  - FastAsyncWorldEdit
  - WorldEdit
authors: [JamieIsGeek]
description: A plugin to make water rise innit
website: https://jamieisgeek.uk
commands:
  event:
    description: Trigger the event
    usage: /<command> <start|stop>
    permission: waterrising.admin

permissions:
  waterrising.notify:
    default: not op

  waterrising.admin:
    default: op